<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="suman" failures="0" tests="8" name="api.test.UserTests2" time="11.212" errors="1" timestamp="2024-01-28T16:46:48 CST" skipped="0">
  <testcase classname="api.test.UserTests2" name="testPostUser" time="6.115"/>
  <system-out/>
  <testcase classname="api.test.UserTests2" name="createListOfUserWithArray" time="2.183"/>
  <system-out/>
  <testcase classname="api.test.UserTests2" name="createListOfUserWithList" time="0.008">
    <error message="Can&#039;t find resource for bundle java.util.PropertyResourceBundle, key post1_url" type="java.util.MissingResourceException">
      <![CDATA[java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key post1_url
at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
at api.endPoints.UserEndPoints2.createUser2(UserEndPoints2.java:38)
at api.test.UserTests2.createListOfUserWithList(UserTests2.java:143)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createListOfUserWithList -->
  <system-out/>
  <testcase classname="api.test.UserTests2" name="testGetUserByName" time="1.108"/>
  <system-out/>
  <testcase classname="api.test.UserTests2" name="logUserIntoTheSystem" time="0.382"/>
  <system-out/>
  <testcase classname="api.test.UserTests2" name="logOut" time="0.273"/>
  <system-out/>
  <testcase classname="api.test.UserTests2" name="testUpdateUswrByName" time="0.857"/>
  <system-out/>
  <testcase classname="api.test.UserTests2" name="testDeleteUserByName" time="0.286"/>
  <system-out/>
</testsuite> <!-- api.test.UserTests2 -->
